let dataES =
    [
      {
        "anoCenso": 2013,
        "cod": 32052081,
        "nome": "CEEJA DE CACHOEIRO DE ITAPEMIRIM",
        "codCidade": 3201209,
        "cidade": "CACHOEIRO DE ITAPEMIRIM",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32021798,
        "nome": "CEEJA DE LINHARES",
        "codCidade": 3203205,
        "cidade": "LINHARES",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32039972,
        "nome": "CEEJA DE VITORIA",
        "codCidade": 3205309,
        "cidade": "VITORIA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32010303,
        "nome": "CEEJA PEDRO ANTONIO VITALI",
        "codCidade": 3201506,
        "cidade": "COLATINA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32080204,
        "nome": "CEET - TALMO LUIZ SILVA",
        "codCidade": 3203130,
        "cidade": "JOAO NEIVA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32038569,
        "nome": "CEET - VASCO COUTINHO",
        "codCidade": 3205200,
        "cidade": "VILA VELHA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32079117,
        "nome": "CENTRO DE APOIO PEDAGOGICO AO DEFICIENTE VISUAL - CAP",
        "codCidade": 3205309,
        "cidade": "VITORIA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32052103,
        "nome": "EE - CEI ATTILA DE ALMEIDA MIRANDA",
        "codCidade": 3201209,
        "cidade": "CACHOEIRO DE ITAPEMIRIM",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 493.51800537109375,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32079958,
        "nome": "EECOR DE COLATINA",
        "codCidade": 3201506,
        "cidade": "COLATINA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32052928,
        "nome": "EEE AUDITIVA LIONS PROF NAPOLEAO ALBUQUERQUE",
        "codCidade": 3201209,
        "cidade": "CACHOEIRO DE ITAPEMIRIM",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32040873,
        "nome": "EEE ORAL E AUDITIVA",
        "codCidade": 3205309,
        "cidade": "VITORIA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32007787,
        "nome": "EEEF - BAIRRO BOA VISTA",
        "codCidade": 3204708,
        "cidade": "SAO GABRIEL DA PALHA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 4.699999809265137,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32038887,
        "nome": "EEEF - BARAO DO RIO BRANCO",
        "codCidade": 3205200,
        "cidade": "VILA VELHA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 4.099999904632568,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32035390,
        "nome": "EEEF - CAMPINHO",
        "codCidade": 3205002,
        "cidade": "SERRA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 4.300000190734863,
        "idebAF": 2.9000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32036094,
        "nome": "EEEF - CARAPEBUS",
        "codCidade": 3205002,
        "cidade": "SERRA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 4.900000095367432,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32052243,
        "nome": "EEEF - CAROLINA PASSOS GAIGHER",
        "codCidade": 3201209,
        "cidade": "CACHOEIRO DE ITAPEMIRIM",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.400000095367432,
        "idebAF": 4.699999809265137,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32043503,
        "nome": "EEEF - CELITA BASTOS GARCIA",
        "codCidade": 3202405,
        "cidade": "GUARAPARI",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.300000190734863,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32052260,
        "nome": "EEEF - CLUBE DO BOSQUE",
        "codCidade": 3201209,
        "cidade": "CACHOEIRO DE ITAPEMIRIM",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.800000190734863,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32052294,
        "nome": "EEEF - CORAMARA",
        "codCidade": 3201209,
        "cidade": "CACHOEIRO DE ITAPEMIRIM",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.699999809265137,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32039697,
        "nome": "EEEF - DANTE MICHELINI",
        "codCidade": 3205200,
        "cidade": "VILA VELHA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.199999809265137,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32038305,
        "nome": "EEEF - DESEMBARGADOR CANDIDO MARINHO",
        "codCidade": 3205200,
        "cidade": "VILA VELHA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.5,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32039700,
        "nome": "EEEF - DOMINGOS JOSE MARTINS - VILA VELHA",
        "codCidade": 3205200,
        "cidade": "VILA VELHA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.099999904632568,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32052278,
        "nome": "EEEF - DONA MARIA SANTANA",
        "codCidade": 3201209,
        "cidade": "CACHOEIRO DE ITAPEMIRIM",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.699999809265137,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32052227,
        "nome": "EEEF - DR ARISTIDES ALEXANDRE CAMPOS",
        "codCidade": 3201209,
        "cidade": "CACHOEIRO DE ITAPEMIRIM",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 4.400000095367432,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32052286,
        "nome": "EEEF - ELISEU LOFEGO",
        "codCidade": 3201209,
        "cidade": "CACHOEIRO DE ITAPEMIRIM",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.5,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32038496,
        "nome": "EEEF - FRANCELINA CARNEIRO SETUBAL",
        "codCidade": 3205200,
        "cidade": "VILA VELHA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.699999809265137,
        "enemMediaGeral": 496.6820068359375,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32070853,
        "nome": "EEEF - FRANCISCO ALVES MENDES",
        "codCidade": 3205002,
        "cidade": "SERRA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 4.699999809265137,
        "idebAF": 4.199999809265137,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32039727,
        "nome": "EEEF - GALDINO ANTONIO VIEIRA",
        "codCidade": 3205200,
        "cidade": "VILA VELHA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 4.0,
        "idebAF": 2.700000047683716,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32052340,
        "nome": "EEEF - INAH WERNECK",
        "codCidade": 3201209,
        "cidade": "CACHOEIRO DE ITAPEMIRIM",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.400000095367432,
        "idebAF": 4.400000095367432,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32060475,
        "nome": "EEEF - ITAOCA",
        "codCidade": 3202801,
        "cidade": "ITAPEMIRIM",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.800000190734863,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32036167,
        "nome": "EEEF - JONES JOSE DO NASCIMENTO",
        "codCidade": 3205002,
        "cidade": "SERRA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 3.799999952316284,
        "idebAF": 2.700000047683716,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32052375,
        "nome": "EEEF - JOSE TAVEIRA DOS SANTOS",
        "codCidade": 3201209,
        "cidade": "CACHOEIRO DE ITAPEMIRIM",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.300000190734863,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32036175,
        "nome": "EEEF - JUDITH LEAO CASTELLO RIBEIRO",
        "codCidade": 3205002,
        "cidade": "SERRA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32036183,
        "nome": "EEEF - MANOEL LOPES",
        "codCidade": 3205002,
        "cidade": "SERRA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 4.900000095367432,
        "idebAF": 3.9000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32043554,
        "nome": "EEEF - MANOEL ROSINDO DA SILVA",
        "codCidade": 3202405,
        "cidade": "GUARAPARI",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.099999904632568,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32057474,
        "nome": "EEEF - MARCONDES DE SOUZA",
        "codCidade": 3203809,
        "cidade": "MUQUI",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 4.800000190734863,
        "idebAF": 4.400000095367432,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32052421,
        "nome": "EEEF - MARIA ANGELICA MARANGONI SANTANA",
        "codCidade": 3201209,
        "cidade": "CACHOEIRO DE ITAPEMIRIM",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.099999904632568,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32055790,
        "nome": "EEEF - MONTEIRO DA SILVA",
        "codCidade": 3203403,
        "cidade": "MIMOSO DO SUL",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.099999904632568,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32055811,
        "nome": "EEEF - PEDRO JOSE VIEIRA",
        "codCidade": 3203403,
        "cidade": "MIMOSO DO SUL",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.400000095367432,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32036027,
        "nome": "EEEF - PREFEITO JOSE MARIA MIGUEL FEU ROSA",
        "codCidade": 3205002,
        "cidade": "SERRA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 4.199999809265137,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32036515,
        "nome": "EEEF - PROF ANNA GOMES",
        "codCidade": 3205002,
        "cidade": "SERRA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.099999904632568,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32035500,
        "nome": "EEEF - PROF JOAO ANTUNES DAS DORES",
        "codCidade": 3205002,
        "cidade": "SERRA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.099999904632568,
        "idebAF": 3.200000047683716,
        "enemMediaGeral": 445.739990234375,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32039816,
        "nome": "EEEF - PROF JORGE ANIZIO BORJAILLE",
        "codCidade": 3205200,
        "cidade": "VILA VELHA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.5,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32061943,
        "nome": "EEEF - PROFESSORA MARIA DA PAZ PIMENTEL",
        "codCidade": 3202207,
        "cidade": "FUNDAO",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.0999999046325684,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32052642,
        "nome": "EEEF - ROTARY",
        "codCidade": 3201209,
        "cidade": "CACHOEIRO DE ITAPEMIRIM",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.099999904632568,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32052650,
        "nome": "EEEF - SANTA CECILIA",
        "codCidade": 3201209,
        "cidade": "CACHOEIRO DE ITAPEMIRIM",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.800000190734863,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32043643,
        "nome": "EEEF - SAO JOSE",
        "codCidade": 3202405,
        "cidade": "GUARAPARI",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.5,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32036540,
        "nome": "EEEF - TAQUARA I",
        "codCidade": 3205002,
        "cidade": "SERRA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 4.599999904632568,
        "idebAF": 3.5999999046325684,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32037473,
        "nome": "EEEF - VIRGINIO PEREIRA",
        "codCidade": 3205002,
        "cidade": "SERRA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 4.900000095367432,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32022999,
        "nome": "EEEF ALEGRE",
        "codCidade": 3205010,
        "cidade": "SOORETAMA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.300000190734863,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32046901,
        "nome": "EEEF ANTONIO CARNEIRO RIBEIRO",
        "codCidade": 3202306,
        "cidade": "GUACUI",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.5999999046325684,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32034563,
        "nome": "EEEF ANTONIO ESTEVES",
        "codCidade": 3201308,
        "cidade": "CARIACICA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.300000190734863,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32021925,
        "nome": "EEEF AUTO GUIMARAES E SOUZA",
        "codCidade": 3203205,
        "cidade": "LINHARES",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.300000190734863,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32009380,
        "nome": "EEEF BRASIL",
        "codCidade": 3200805,
        "cidade": "BAIXO GUANDU",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.900000095367432,
        "idebAF": 5.599999904632568,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32034458,
        "nome": "EEEF CASTELO BRANCO",
        "codCidade": 3201308,
        "cidade": "CARIACICA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 4.900000095367432,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32034580,
        "nome": "EEEF CELESTINO DE ALMEIDA",
        "codCidade": 3201308,
        "cidade": "CARIACICA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32003498,
        "nome": "EEEF COTAXE",
        "codCidade": 3202108,
        "cidade": "ECOPORANGA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32002939,
        "nome": "EEEF DANIEL COMBONI",
        "codCidade": 3202108,
        "cidade": "ECOPORANGA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 4.400000095367432,
        "idebAF": 4.099999904632568,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32030142,
        "nome": "EEEF DOMINGOS PERIM",
        "codCidade": 3205069,
        "cidade": "VENDA NOVA DO IMIGRANTE",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.599999904632568,
        "idebAF": 5.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32017243,
        "nome": "EEEF DR EDWARD ABREU DO NASCIMENTO",
        "codCidade": 3204054,
        "cidade": "PEDRO CANARIO",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32017995,
        "nome": "EEEF DR EMILIO ROBERTO ZANOTTI",
        "codCidade": 3204906,
        "cidade": "SAO MATEUS",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.599999904632568,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32011709,
        "nome": "EEEF DR MOACIR AVIDOS",
        "codCidade": 3202256,
        "cidade": "GOVERNADOR LINDENBERG",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.199999809265137,
        "idebAF": 4.199999809265137,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32033753,
        "nome": "EEEF DR SOUZA ARAUJO",
        "codCidade": 3201308,
        "cidade": "CARIACICA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 4.199999809265137,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32018045,
        "nome": "EEEF EGIDIO BORDONI",
        "codCidade": 3204906,
        "cidade": "SAO MATEUS",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.400000095367432,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32033788,
        "nome": "EEEF EULALIA MOREIRA",
        "codCidade": 3201308,
        "cidade": "CARIACICA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.4000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32033800,
        "nome": "EEEF GENERAL TIBURCIO",
        "codCidade": 3201308,
        "cidade": "CARIACICA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.300000190734863,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32037171,
        "nome": "EEEF GERMANO ANDRE LUBE",
        "codCidade": 3205002,
        "cidade": "SERRA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.099999904632568,
        "idebAF": 4.400000095367432,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32034610,
        "nome": "EEEF GLADISTON REGIS BARBOSA",
        "codCidade": 3201308,
        "cidade": "CARIACICA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 4.900000095367432,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32022050,
        "nome": "EEEF JOSE DE CALDAS BRITO",
        "codCidade": 3203205,
        "cidade": "LINHARES",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.799999952316284,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32034687,
        "nome": "EEEF JOSE MARIA FERREIRA",
        "codCidade": 3201308,
        "cidade": "CARIACICA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.400000095367432,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32033826,
        "nome": "EEEF JOSE RODRIGUES COUTINHO",
        "codCidade": 3201308,
        "cidade": "CARIACICA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 4.300000190734863,
        "idebAF": 4.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32030150,
        "nome": "EEEF LIBERAL ZANDONADI",
        "codCidade": 3205069,
        "cidade": "VENDA NOVA DO IMIGRANTE",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 7.0,
        "idebAF": 4.099999904632568,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32022069,
        "nome": "EEEF LUIZ DE CAMOES",
        "codCidade": 3203205,
        "cidade": "LINHARES",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.800000190734863,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32033842,
        "nome": "EEEF MANOEL PASCHOAL DE OLIVEIRA",
        "codCidade": 3201308,
        "cidade": "CARIACICA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 4.5,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32040377,
        "nome": "EEEF MARIA ERICINA SANTOS",
        "codCidade": 3205309,
        "cidade": "VITORIA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32002971,
        "nome": "EEEF PATRIMONIO PRATA DOS BAIANOS",
        "codCidade": 3202108,
        "cidade": "ECOPORANGA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32035241,
        "nome": "EEEF PAUTILA RODRIGUES XAVIER",
        "codCidade": 3201308,
        "cidade": "CARIACICA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.900000095367432,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32017286,
        "nome": "EEEF PEDRO CANARIO RIBEIRO",
        "codCidade": 3204054,
        "cidade": "PEDRO CANARIO",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.599999904632568,
        "idebAF": 3.9000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32033915,
        "nome": "EEEF PRESIDENTE MEDICI",
        "codCidade": 3201308,
        "cidade": "CARIACICA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 4.699999809265137,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32022123,
        "nome": "EEEF PRINCESA ISABEL",
        "codCidade": 3203205,
        "cidade": "LINHARES",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 4.599999904632568,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32034830,
        "nome": "EEEF PROF AUGUSTO CARVALHO",
        "codCidade": 3201308,
        "cidade": "CARIACICA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.300000190734863,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32067771,
        "nome": "EEEF PROF MARIUZA SECHIN",
        "codCidade": 3201308,
        "cidade": "CARIACICA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 4.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32007825,
        "nome": "EEEF PROFESSOR CARLOS DIAS MIRANDA CUNHA",
        "codCidade": 3204708,
        "cidade": "SAO GABRIEL DA PALHA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.699999809265137,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32045344,
        "nome": "EEEF PROFESSOR LELLIS",
        "codCidade": 3200201,
        "cidade": "ALEGRE",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.699999809265137,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32035470,
        "nome": "EEEF PROFª ADEVALNI AZEVEDO",
        "codCidade": 3205002,
        "cidade": "SERRA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 3.700000047683716,
        "idebAF": 3.9000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32023049,
        "nome": "EEEF REGINA BOLSSANELLO FORNAZIER",
        "codCidade": 3205010,
        "cidade": "SOORETAMA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.199999809265137,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32002998,
        "nome": "EEEF SANTA TEREZINHA",
        "codCidade": 3202108,
        "cidade": "ECOPORANGA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32034920,
        "nome": "EEEF STELLITA RAMOS",
        "codCidade": 3201308,
        "cidade": "CARIACICA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.799999952316284,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32034962,
        "nome": "EEEF TIRADENTES",
        "codCidade": 3201308,
        "cidade": "CARIACICA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 4.800000190734863,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32008481,
        "nome": "EEEF VALERIO",
        "codCidade": 3205176,
        "cidade": "VILA VALERIO",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.699999809265137,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32000928,
        "nome": "EEEF VARGEM ALEGRE",
        "codCidade": 3200904,
        "cidade": "BARRA DE SAO FRANCISCO",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32034970,
        "nome": "EEEF VENTINO DA COSTA BRANDAO",
        "codCidade": 3201308,
        "cidade": "CARIACICA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32038852,
        "nome": "EEEFM - ADOLFINA ZAMPROGNO",
        "codCidade": 3205200,
        "cidade": "VILA VELHA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 4.099999904632568,
        "idebAF": 4.0,
        "enemMediaGeral": 468.3659973144531,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32040695,
        "nome": "EEEFM - AFLORDIZIO CARVALHO DA SILVA",
        "codCidade": 3205309,
        "cidade": "VITORIA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 2.4000000953674316,
        "enemMediaGeral": 451.7720031738281,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32038488,
        "nome": "EEEFM - AGENOR DE SOUZA LE",
        "codCidade": 3205200,
        "cidade": "VILA VELHA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.799999952316284,
        "enemMediaGeral": 485.4960021972656,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32059310,
        "nome": "EEEFM - AGOSTINHO AGRIZZI",
        "codCidade": 3205036,
        "cidade": "VARGEM ALTA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.5,
        "idebAF": 4.699999809265137,
        "enemMediaGeral": 495.7860107421875,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32052189,
        "nome": "EEEFM - AGOSTINHO SIMONATO",
        "codCidade": 3201209,
        "cidade": "CACHOEIRO DE ITAPEMIRIM",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 475.2460021972656,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32041560,
        "nome": "EEEFM - ALMIRANTE BARROSO",
        "codCidade": 3205309,
        "cidade": "VITORIA",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.700000047683716,
        "enemMediaGeral": 490.2380065917969,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32043490,
        "nome": "EEEFM - ANGELICA PAIXAO",
        "codCidade": 3202405,
        "cidade": "GUARAPARI",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 5.300000190734863,
        "enemMediaGeral": 507.5480041503906,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 32055820,
        "nome": "EEEFM - ANTONIO ACHA",
        "codCidade": 3203403,
        "cidade": "MIMOSO DO SUL",
        "estado": "ES",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      }
    ]

    export default dataES;