let es = [
  {
    cod: 32039972,
    nome: "CEEJA DE VITORIA",
    codCidade: 3205309,
    cidade: "VITORIA",
    estado: "ES",
    regiao: "Sudeste",
  },
  {
    cod: 32079117,
    nome: "CENTRO DE APOIO PEDAGOGICO AO DEFICIENTE VISUAL - CAP",
    codCidade: 3205309,
    cidade: "VITORIA",
    estado: "ES",
    regiao: "Sudeste",
  },
  {
    cod: 32040873,
    nome: "EEE ORAL E AUDITIVA",
    codCidade: 3205309,
    cidade: "VITORIA",
    estado: "ES",
    regiao: "Sudeste",
  },
  {
    cod: 32040377,
    nome: "EEEF MARIA ERICINA SANTOS",
    codCidade: 3205309,
    cidade: "VITORIA",
    estado: "ES",
    regiao: "Sudeste",
  },
  {
    cod: 32040695,
    nome: "EEEFM - AFLORDIZIO CARVALHO DA SILVA",
    codCidade: 3205309,
    cidade: "VITORIA",
    estado: "ES",
    regiao: "Sudeste",
  },
  {
    cod: 32041560,
    nome: "EEEFM - ALMIRANTE BARROSO",
    codCidade: 3205309,
    cidade: "VITORIA",
    estado: "ES",
    regiao: "Sudeste",
  },
  {
    cod: 32040717,
    nome: "EEEFM - DES CARLOS XAVIER PAES BARRETO",
    codCidade: 3205309,
    cidade: "VITORIA",
    estado: "ES",
    regiao: "Sudeste",
  },
  {
    cod: 32063199,
    nome: "EEEFM - ELZA LEMOS ANDREATTA",
    codCidade: 3205309,
    cidade: "VITORIA",
    estado: "ES",
    regiao: "Sudeste",
  },
  {
    cod: 32040300,
    nome: "EEEFM - HILDEBRANDO LUCAS",
    codCidade: 3205309,
    cidade: "VITORIA",
    estado: "ES",
    regiao: "Sudeste",
  },
  {
    cod: 32040725,
    nome: "EEEFM - MAJOR ALFREDO PEDRO RABAIOLI",
    codCidade: 3205309,
    cidade: "VITORIA",
    estado: "ES",
    regiao: "Sudeste",
  },
  {
    cod: 32040733,
    nome: "EEEFM - MARIA ORTIZ",
    codCidade: 3205309,
    cidade: "VITORIA",
    estado: "ES",
    regiao: "Sudeste",
  },
  {
    cod: 32041640,
    nome: "EEEM - ARNULPHO MATTOS",
    codCidade: 3205309,
    cidade: "VITORIA",
    estado: "ES",
    regiao: "Sudeste",
  },
  {
    cod: 32040067,
    nome: "EEEM - COLEGIO ESTADUAL DO ESPIRITO SANTO",
    codCidade: 3205309,
    cidade: "VITORIA",
    estado: "ES",
    regiao: "Sudeste",
  },
  {
    cod: 32040288,
    nome: "EEEM - GOMES CARDIM",
    codCidade: 3205309,
    cidade: "VITORIA",
    estado: "ES",
    regiao: "Sudeste",
  },
  {
    cod: 32040334,
    nome: "EEEM - IRMA MARIA HORTA",
    codCidade: 3205309,
    cidade: "VITORIA",
    estado: "ES",
    regiao: "Sudeste",
  },
  {
    cod: 32040784,
    nome: "EEEM - PROF FERNANDO DUARTE RABELO - VITORIA",
    codCidade: 3205309,
    cidade: "VITORIA",
    estado: "ES",
    regiao: "Sudeste",
  },
  {
    cod: 32079338,
    nome: "EEEM - PROF RENATO JOSE DA COSTA PACHECO",
    codCidade: 3205309,
    cidade: "VITORIA",
    estado: "ES",
    regiao: "Sudeste",
  },
  {
    cod: 32080611,
    nome: "NAAHS - NUCLEO DE ATIVIDADES DE ALTAS HAB-SUPERDOTACAO",
    codCidade: 3205309,
    cidade: "VITORIA",
    estado: "ES",
    regiao: "Sudeste",
  },
];

export default function handler(req, res) {
  res.status(200).json({ name: "Bruno" });
}
